language: c

compiler:
    - clang
    - gcc

before_script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DOCTASPIRE_CORE_COVERAGE:BOOL=ON ..

script:
    - make
    - test/octaspire-core-test-runner
    - cd test/CMakeFiles/octaspire-core-test-runner.dir
    - gcov *.gcno

after_success:
      - bash <(curl -s https://codecov.io/bash)

