language: c

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install gdb valgrind -y; fi
      #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install valgrind; fi

before_script:
    - cd release/
    - CORE_TRAVIS_BUILD_DIR=$(pwd)

script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ulimit -c unlimited -S; how-to-build/linux.sh $CC; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then how-to-build/macOS.sh $CC; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then valgrind --leak-check=full --error-exitcode=1 ./octaspire-core-unit-test-runner; fi
    - ./octaspire-core-unit-test-runner

# 'after_failure'-hook in modified form from:
# jsteemann.github.io/blog/2014/10/30/getting-core-dumps-of-failed-travisci-builds/
after_failure:
    - cd "$CORE_TRAVIS_BUILD_DIR"
    - COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1)
    - if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" octaspire-core-unit-test-runner -ex "thread apply all bt" -ex "set pagination 0" -batch; fi
